### PR TITLE
Fix multiple czech.lng issues

### PR DESCRIPTION
**Pull request by geby**
Hi, I just made some tweaks to my czech.lng translate, like fix encoding or fix grammar casing...

### CODE REVIEW

**Comment by geby** [comment]
This one is most up to date. The PR #5 was mine too, but I could not find a way to update the file there...

**Comment by EmperorJake** [comment]
The encoding was a bit weird, I see that now. While it looks correct in game the file looks broken in my text editor so I had broken it trying to fix it (while the original FIRS Czech file looks normal, oddly enough). A lot of the letters with accents were completely wrong but it seems to be correct now.

Also I had to change the plural to 10 to get it to compile, that's how it is in the original FIRS file but let me know if something went wrong there.

**Comment by EmperorJake** [comment]
Screenshot at 2021-08-23 14-44-29

Also may I ask why your translation is so different from the original FIRS one?

**Comment by geby** [comment]
It seem to be correctly encoded now.
The plurals are in Czech so complicated. If it is same in FIRS, it is corretly... The signed word grammar codes were taken from FIRS.
The rest was, however, made from scratch using only XIS english.lng... Because of that, it is different. I tried to make the translate better in my opinion, for example I made new names for industry serving stations to look like real-life Czech stop names, as opposed to FIRS naming it (at least in Czech translate) after products of the industry.
I themed the stops to be actually related to the industry, sometimes I got inspired by English string, for example: EN: James Watt street CZ: Františka Křižíka (František Křižík was Czech electrical engineer, who for example improved the arc lamp, or made first Czech electric trams and trains)

**Pull request merged**
